//
//  Constants.h
//  DeliCafe
//
//  Created by   on 10/17/14.
//  Copyright (c) 2014 softprodigy. All rights reserved.
//

#import <Foundation/Foundation.h>

//@protocol Constants <NSObject>

//@end
#define SCREEN_WIDTH ((([UIApplication sharedApplication].statusBarOrientation == UIInterfaceOrientationPortrait) || ([UIApplication sharedApplication].statusBarOrientation == UIInterfaceOrientationPortraitUpsideDown)) ? [[UIScreen mainScreen] bounds].size.width : [[UIScreen mainScreen] bounds].size.height)
//http://www.softprodigy.com/store/admin

#define Is_IPhone4 (([[UIScreen mainScreen] bounds].size.height-480)?NO:YES)
#define Is_IPhone5 (([[UIScreen mainScreen] bounds].size.height-568)?NO:YES)
#define Is_IPhone6 (([[UIScreen mainScreen] bounds].size.height-667)?NO:YES)
#define Is_IPhone6Plus (([[UIScreen mainScreen] bounds].size.height-736)?NO:YES)
#define ISPHONE5 ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(640, 1136), [[UIScreen mainScreen] currentMode].size) : NO)

#define isiPhoneDevice ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPhone)

#define baseURL1 @"http://rainbo.in/minimart/miniapi/"


//color constants
#define statusBarColor [UIColor colorWithRed:140.0/255.0 green:140.0/255.0 blue:140.0/255.0 alpha:1.0]
#define topBarColor [UIColor colorWithRed:238/255.0 green:238/255.0 blue:238/255.0 alpha:1.0]
#define ButtonColor [UIColor colorWithRed:22.0/255.0 green:127.0/255.0 blue:68.0/255.0 alpha:1.0]
#define PriceColor [UIColor colorWithRed:244.0/255.0 green:128.0/255.0 blue:32.0/255.0 alpha:1.0]
#define saffronColor [UIColor colorWithRed:255.0/255.0 green:125.0/255.0 blue:0.0/255.0 alpha:1.0]
#define GreenColor [UIColor colorWithRed:12.0/255.0 green:116.0/255.0 blue:63.0/255.0 alpha:1.0]
#define BlueColor [UIColor colorWithRed:62.0/255.0 green:78.0/255.0 blue:189.0/255.0 alpha:1.0]

//words constant

#define tViewMore @"View More"
#define tSearchYourItem @"Search Your Item"
#define tSortBy @"Sort By"
#define tSORTBY @"SORT BY"
#define tAtoZ @"A to Z"
#define tZtoA @"Z to A"
#define tPriceLowtoHigh @"Price Low to High"
#define tPriceHightoLow @"Price High to Low"
#define tNoInternet @"There is no internet connection"
#define tProfile @"Profile"
#define tMyOrders @"My Orders"
#define tAppInfo @"App Info"
#define tLogin @"Login"
#define tLogout @"Logout"
#define tMyWishList @"My WishList"
#define tNotifications @"Notifications"
#define tYourCartIsEmpty @"Your cart is empty"
#define tOK @"Ok"
#define tPleaseRateOnGoBuyo @"Please rate the App!"
#define tIfyoulikeitwedliketoknow @"If you like it we'd like to know."
#define tRateItNow @"Rate It Now"
#define tRemindMeLater @"Remind Me Later"
#define tNoThanks @"No, Thanks"
#define tNomoreitemsinthelist @"No more items in the list."
#define tNoItemtoView @"No Item to View"
#define tWishlist @"Wishlist"
#define tOopsSomethingwentwrong @"Oops!Something went wrong."
#define tPleasespecifytheproductoption @"Please specify the product's option(s).to add the product to cart."
#define tLOGOUT @"LOGOUT"
#define tSave @"Save"
#define tChangePassword @"Change Password"
#define tCancel @"Cancel"
#define tSubmitReview @"Submit Review"
#define tBy @"By"
#define tNoReviewBethefirstone @"No Review. Be the first one to Review this product."
#define tCommentsReviews @"Comments & Reviews"
#define tProductReviews @"Product Reviews"
#define tOverallRating @"Overall Rating:"
#define tAddReview @"Add Review"
#define tHowDoYouRateThisProduct @"How Do You Rate This Product!!"
#define tLetUsKnowYourThoughts @"Let Us Know Your Thoughts"
#define tSummaryofYourReview @"Summary of Your Review"
#define tWhatisyourNickname @"What is your Nickname?"
#define tValue @"Value"
#define tQuality @"Quality"
#define tPrice @"Price"
#define tSearch @"Search"
#define tFirstName @"First Name"
#define tLastName @"Last Name"
#define tEMailAddress @"E-Mail Address"
#define tCurrentPassword @"Current Password"
#define tNewPassword @"New Password"
#define tConfirmPassword @"Confirm Password"
#define tAreyousureyouwanttologout @"Are you sure you want to logout?"
#define tPleasefillthefirstname @"Please fill the first name!"
#define tPleasefillthelastname @"Please fill the last name!"
#define tPleasefilltheCurrentPassword @"Please fill the Current Password!"
#define tPleasefilltheNewPassword @"Please fill the New Password!"
#define tPleasefilltheConfirmPassword @"Please fill the Confirm Password!"
#define tPasswordshouldbeatleast6characters @"Password should be at least 6 characters."
#define tPassworddoesntmatch @"Password doesn't match!"
#define tLoginUnsuccessfull @"Login Unsuccessfull!"
#define tPassword @"Password"
#define tEmailformatisnotcorrect @"Email format is not correct."
#define tPleasefillalldetails @"Please fill all details."
#define tHAPPYTOHAVEYOUHERE @"HAPPY TO HAVE YOU HERE"
#define tPleaseloginbelowwithyourdetails @"Please login below with your details"
#define tForgotPassword @"Forgot Password?"
#define tRegisterwithus @"Register with us"
#define tDontHaveAccountyet  @"Don't Have Account yet? "
#define tAlert @"Alert"
#define tNotification @"Notification"
#define tQty @"Qty"
#define tOutofStock @"Out of Stock"
#define tCartdetails @"Cart details"
#define tSUBTOTAL @"SUBTOTAL"
#define tDISCOUNT @"DISCOUNT"
#define tTAXES @"TAXES"
#define tDELIVERYCHARGES @"DELIVERY CHARGES"
#define tORDERTOTAL @"ORDER TOTAL"
#define tHaveaCoupon @"Have a Coupon ?"
#define tRemoveCoupon @"Remove Coupon"
#define tCONFIRM @"CONFIRM"
#define tEnteryourcouponcodehere @"Enter your coupon code here..."
#define tCouponCode @"Coupon Code"
#define tAPPLY @"APPLY"
#define tITLOOKSLIKEYOUARENOTLOGGEDIN @"IT LOOKS LIKE YOU ARE NOT LOGGED IN!"
#define tContinueAsaGuestUser @"Continue As a Guest User"
#define tOR @"OR"
#define tLoginNow @"Login Now"
#define tCouponApplied @"Coupon Applied."
#define tYouritem @"Your item"
#define twillbedeletedConfirmtocontinue @"will be deleted. Confirm to delete."
#define tConfirmDelete @"Confirm Delete"
#define tPleaseentercouponcode @"Please enter coupon code."
#define tPleaseremoveproductswhichareoutofstock @"Please remove products which are out of stock."
#define tDownload @"Download"
#define tOrderId @"OrderId-"
#define tLOSTYOURPASSWORD @"LOST YOUR PASSWORD?"
#define tSimplytypeinyouremailtoreset @"Simply type in your email to reset"
#define tEnterYourEmail @"Enter Your Email"
#define tResetPassword @"Reset Password"
#define tPleasefillthevalidemailaddress @"Please fill the valid email address!"
#define tViewOrder @"View Order"
#define tNoordersfound @"No orders found"
#define tOrderSummary @"Order Summary"
#define tCancelOrder @"Cancel Order"
#define tDeliveryAddress @"Delivery Address"
#define tGrandTotal @"Grand Total"
#define tStatus @"Status"
#define tOrderID @"Order ID"
#define tTotalItemsOrdered @"Total Items Ordered"
#define tShippingwillnotbedoneforthisproduct @"Shipping will not be done for this product."
#define tRecentNotifications @"Recent Notifications (10)"
#define tNoNotificationtoshow @"No Notification to show."
#define tQuantity @"Quantity :"
#define tPrice1 @"Price :"
#define tOrderReview @"Order Review"
#define tPLACENOW @"PLACE NOW"
#define tNoresultfound @"No result found"
#define tPleasetypesomewords @"Please type some words."
#define tSearchfor @"Search for"
#define tInStock @"In Stock"
#define tSearch @"Search"
#define tADDTOCART @"  ADD TO CART"
#define tBUYNOW @"  BUY NOW"
#define tDescription @"Description"
#define tAdditionalInformation @"Additional Information"
#define tReviews @"Reviews"
#define tRelatedProducts @"Related Products"
#define tGrouped @"Grouped"
#define tOptions @"Options"
#define tDone @"Done"
#define tLinksSamples @"Links & Samples"
#define tSelect @"Select"
#define tSelectDateTime @"   Select Date & Time"
#define tSetTime @"Set Time"
#define tTime @"Time"
#define tProductisoutofstock @"Product is out of stock."
#define tConfirmlogin @"Confirm login"
#define tPleaseLogintoaddremoveproducttowishlistConfirmtocontinue @"Please Login to add product to wishlist. confirm to continue."
#define tREADYTOGETSTARTED @"READY TO GET STARTED?"
#define tFillyourdetailsbelowtoregister @"Fill your details below to register"
#define tSignUpforNewsletter @"Sign Up for Newsletter"
#define tRegister @"Register"
#define tNoitemsfound @"No items found"
#define tPleaseselectshippingandpaymentmethods @"Please select shipping and payment methods."
#define tPh @"Ph"
#define tYourordercannotbecompleted @"Your order cannot be completed at this time as there is no shipping methods available for it. Please make necessary changes in your shipping address."
#define tNO @"NO"
#define tNext @"Next"
#define tPlease select the Country name field @"Please select the Country name field!"
#define tBillingAddress @"Billing Address"
#define tChange @"Change"
#define tShippingAddress @"Shipping Address"
#define tOrderSummary @"Order Summary"
#define tSelectAShippingMethod @"Select A Shipping Method"
#define tAmountDetails @"Amount Details"
#define tSELECTAPAYMETHOD @"SELECT A PAY METHOD"
#define tPayPal @"PayPal"
#define tMakepaymentusingPayumoney @"Make payment using Payumoney"
#define tCashondelivery @"Cash on delivery (COD)"
#define tCashondeliveryisavailableonlyforselectedlocations @"Cash on delivery is available only for selected locations."
#define tChequeMoneyOrder @"Cheque Money Order"
#define tPayorderusingchequemoneyorder @"Pay order using cheque money order"
#define tBankTransferPayment @"Bank Transfer Payment"
#define tFree @"Free"
#define tNoPaymentInformationRequired @"No Payment Information Required"
#define tYOURORDERHASBEENRECEIVED @"YOUR ORDER HAS BEEN RECEIVED"
#define tThanksForShoppingWithUs @"Thanks For Shopping With Us"
#define tYourorderIDis @"Your order ID is"
#define tYouwillrecieveanorderconfirmationemailwithdetailsofyourorder @"You will recieve an order confirmation email with details of your order."
#define tCONTINUESHOPPING @"CONTINUE SHOPPING"
#define tThisisademostoreAny @"This is a demo store. Any orders placed through this store will not be honored or fulfilled."
#define tAlreadyaMember @"Already a Member?"
#define tLoginhere @"Login here"
#define tPleaseselecttheCountrynamefield @"Please select the Country name field!"
#define tPleasefilltheFirstnamefield @"Please fill the First name field!"
#define tPleasefilltheLastnamefield @"Please fill the Last name field!"
#define tPleasefilltheAddressfield @"Please fill the Address 1 field!"
#define tPleasefilltheStatefield @"Please fill the State field!"
#define tPleasefilltheTown @"Please fill the Town / City field!"
#define tPleasefillthePostCodefield @"Please fill the Post Code field!"
#define tPleasefillthePhonefield @"Please fill the Phone field!"
#define tPhonenumbershouldhave10to12digits @"Phone number should have 10 to 12 digits."
#define tPleasefilltheEmailfield @"Please fill the Email field!"
#define tBillingDetails @"Billing Details"
#define tShippingDetails @"Shipping Details"
#define tSameasMyBillingAddress @"Same as My Billing Address"
#define tSelectCountry @"Select Country"
#define tAddressLine1 @"Address Line 1"
#define tAddressLine2 @"Address Line 2"
#define tTownCity @"Town / City"
#define tStateRegion @"State / Region"
#define tPostcodeZip @"Postcode / Zip"
#define tPhone @"Phone"
#define tPlaceOrder @"Place Order"
#define tPleaseLogintoavailthisproduct @"Please Login to avail this product."
#define tPleaseselectoneofeachoftheratingsabove @"Please select one of each of the ratings above."
#define tPleaseprovideyourNickname @"Please provide your Nickname."
#define tPleaseprovidesummaryofyourReview @"Please provide summary of your Review."
#define tPleasetypeyourthoughtsfirst @"Please type your thoughts first."
#define tSelectRegion @"Select Region"
#define tYES @"YES"
#define tYourtransactionhasbeencancelled @"Your transaction has been cancelled."
#define tOff @"Off"
#define tSharingURL @"Sharing URL"
#define tPleaseenterPincode @"Please enter Pincode."
#define tDate @"Date"
#define tDeliveryoptionfor @"Delivery option for"
#define tSameDayDispatch @"Same Day Dispatch"
#define tDeliveryWithin @"Delivery Within"
#define tdays @"day(s)"
#define tYoucannotratethisproductrightnowasRatingsaredisabledtemporarily @"You can not rate this product right now as Ratings are disabled temporarily."
#define tWaitForSubscriptionoftheapp @"Wait For Subscription of the app!"
#define tHome @"Home"
#define tSelectLanguage @"Select Language"
#define tLanguageSettings @"Language Settings"
#define tLanguage @"Language"
#define tDeliveryOptions @"Delivery Options"
#define tEnterPincode @"Enter Pincode"
#define tCheck @"Check"
#define t @""
#define t @""
#define t @""
#define t @""
#define t @""
#define t @""





